version: '3'
services:

  nginx:
    build: ./nginx/
    ports:
      - 80:80
    links:
      - php
    volumes:
      - .:/var/www/html

  php:
    image: php:7.0-fpm
    expose:
      - 9000
    volumes:
      - .:/var/www/html